<option value="2">Afghanistan</option>
<option value="3">Albania</option>
<option value="4">Algeria</option>
<option value="5">American Samoa</option>
<option value="6">Andorra</option>
<option value="7">Angola</option>
<option value="8">Anguilla</option>
<option value="9">Antarctica</option>
<option value="10">Antigua And Barbuda</option>
<option value="11">Argentina</option>
<option value="12">Armenia</option>
<option value="13">Aruba</option>
<option value="14">Australia</option>
<option value="15">Austria</option>
<option value="16">Azerbaijan</option>
<option value="17">Bahamas</option>
<option value="18">Bahrain</option>
<option value="19">Bangladesh</option>
<option value="20">Barbados</option>
<option value="200">Belarus</option>
<option value="21">Belgium</option>
<option value="22">Belize</option>
<option value="23">Benin</option>
<option value="24">Bermuda</option>
<option value="25">Bhutan</option>
<option value="26">Bolivia</option>
<option value="27">Bosnia and Herzegovina</option>
<option value="28">Botswana</option>
<option value="29">Brazil</option>
<option value="30">British Indian Ocean Territory</option>
<option value="201">British Virgin Islands</option>
<option value="31">Brunei Darussalam</option>
<option value="32">Bulgaria</option>
<option value="33">Burkina Faso</option>
<option value="34">Burundi</option>
<option value="35">Cambodia</option>
<option value="36">Cameroon</option>
<option value="37">Canada</option>
<option value="38">Cape Verde</option>
<option value="39">Cayman Islands</option>
<option value="40">Central African Republic</option>
<option value="41">Chad</option>
<option value="42">Chile</option>
<option value="43">China</option>
<option value="44">Christmas Island</option>
<option value="45">Cocos (Keeling) Islands</option>
<option value="46">Colombia</option>
<option value="202">Comoros</option>
<option value="203">Congo Brazzaville</option>
<option value="204">Congo Democratic Republic</option>
<option value="205">Cook Islands</option>
<option value="47">Costa Rica</option>
<option value="206">Cote d Ivoire</option>
<option value="48">Croatia (Hrvatska)</option>
<option value="207">Cuba</option>
<option value="49">Cyprus</option>
<option value="50">Czech Republic</option>
<option value="51">Denmark</option>
<option value="52">Djibouti</option>
<option value="53">Dominica</option>
<option value="54">Dominican Republic</option>
<option value="55">East Timor</option>
<option value="56">Ecuador</option>
<option value="57">Egypt</option>
<option value="58">El Salvador</option>
<option value="59">Equatorial Guinea</option>
<option value="60">Eritrea</option>
<option value="61">Estonia</option>
<option value="62">Ethiopia</option>
<option value="63">Faroe Islands</option>
<option value="64">Fiji</option>
<option value="65">Finland</option>
<option value="66">France</option>
<option value="67">French Guiana</option>
<option value="68">French Polynesia</option>
<option value="69">Gabon</option>
<option value="70">Gambia</option>
<option value="71">Georgia</option>
<option value="72">Germany</option>
<option value="73">Ghana</option>
<option value="74">Gibraltar</option>
<option value="75">Greece</option>
<option value="76">Greenland</option>
<option value="77">Grenada</option>
<option value="78">Guadeloupe</option>
<option value="79">Guam</option>
<option value="80">Guatemala</option>
<option value="81">Guinea</option>
<option value="238">Guinea Bissau</option>
<option value="82">Guyana</option>
<option value="83">Haiti</option>
<option value="84">Holy See (Vatican City State)</option>
<option value="85">Honduras</option>
<option value="86">Hong Kong SAR, PRC</option>
<option value="87">Hungary</option>
<option value="88">Iceland</option>
<option value="89">India</option>
<option value="90">Indonesia</option>
<option value="208">Iran</option>
<option value="209">Iraq</option>
<option value="91">Ireland</option>
<option value="92">Israel</option>
<option value="210">Isreal</option>
<option value="93">Italy</option>
<option value="94">Jamaica</option>
<option value="95">Japan</option>
<option value="96">Jordan</option>
<option value="97">Kazakhstan</option>
<option value="98">Kenya</option>
<option value="211">Kiribati</option>
<option value="99">Korea, Republic of</option>
<option value="100">Kuwait</option>
<option value="101">Kyrgyzstan</option>
<option value="102">Lao, People's Dem. Rep.</option>
<option value="239">Laos</option>
<option value="103">Latvia</option>
<option value="104">Lebanon</option>
<option value="105">Lesotho</option>
<option value="212">Liberia</option>
<option value="106">Libya</option>
<option value="107">Liechtenstein</option>
<option value="108">Lithuania</option>
<option value="109">Luxembourg</option>
<option value="110">Macau</option>
<option value="111">Macedonia</option>
<option value="112">Madagascar</option>
<option value="113">Malawi</option>
<option value="114">Malaysia</option>
<option value="115">Maldives</option>
<option value="116">Mali</option>
<option value="117">Malta</option>
<option value="118">Marshall Islands</option>
<option value="119">Martinique</option>
<option value="120">Mauritania</option>
<option value="121">Mauritius</option>
<option value="213">Mayotte</option>
<option value="122">Mexico</option>
<option value="214">Micronesia</option>
<option value="123">Moldova, Republic Of</option>
<option value="124">Monaco</option>
<option value="125">Mongolia</option>
<option value="126">Montenegro</option>
<option value="127">Montserrat</option>
<option value="128">Morocco</option>
<option value="129">Mozambique</option>
<option value="215">Myanmar</option>
<option value="130">Namibia</option>
<option value="216">Nauru</option>
<option value="131">Nepal</option>
<option value="132">Netherlands</option>
<option value="133">Netherlands Antilles</option>
<option value="134">New Caledonia</option>
<option value="135">New Zealand</option>
<option value="136">Nicaragua</option>
<option value="137">Niger</option>
<option value="138">Nigeria</option>
<option value="217">Niue Island</option>
<option value="139">Norfolk Island</option>
<option value="218">North Mariana Islands</option>
<option value="140">Norway</option>
<option value="141">Oman</option>
<option value="142">Pakistan</option>
<option value="219">Palau</option>
<option value="143">Palestine</option>
<option value="144">Panama</option>
<option value="220">Papua New Guinea</option>
<option value="145">Paraguay</option>
<option value="146">Peru</option>
<option value="147">Philippines</option>
<option value="148">Poland</option>
<option value="149">Portugal</option>
<option value="150">Puerto Rico </option>
<option value="151">Qatar</option>
<option value="152">Reunion</option>
<option value="153">Romania</option>
<option value="154">Russia</option>
<option value="155">Rwanda</option>
<option value="156">Saint Kitts And Nevis</option>
<option value="157">Saint Lucia</option>
<option value="158">Saint Vincent And the Grenadines</option>
<option value="159">Samoa</option>
<option value="160">San Marino</option>
<option value="221">Sao Tome and Principe</option>
<option value="161">Saudi Arabia</option>
<option value="162">Senegal</option>
<option value="163">Serbia</option>
<option value="164">Seychelles</option>
<option value="165">Sierra Leone</option>
<option value="166">Singapore</option>
<option value="167">Slovak Republic</option>
<option value="168">Slovenia</option>
<option value="222">Solomon Islands</option>
<option value="223">Somalia</option>
<option value="169">South Africa</option>
<option value="224">South Korea</option>
<option value="170">Spain</option>
<option value="171">Sri Lanka</option>
<option value="225">St Kitts and Nevis</option>
<option value="226">St Lucia</option>
<option value="227">St Vincent</option>
<option value="172">St. Pierre And Miquelon</option>
<option value="228">Sudan</option>
<option value="173">Suriname</option>
<option value="174">Swaziland</option>
<option value="175">Sweden</option>
<option value="176">Switzerland</option>
<option value="229">Syria</option>
<option value="177">Taiwan</option>
<option value="178">Tajikistan</option>
<option value="179">Tanzania, United Republic Of</option>
<option value="180">Thailand</option>
<option value="181">Togo</option>
<option value="182">Tonga</option>
<option value="183">Trinidad And Tobago</option>
<option value="230">Trinidad Tobago</option>
<option value="184">Tunisia</option>
<option value="185">Turkey</option>
<option value="186">Turkmenistan</option>
<option value="187">Turks And Caicos Islands</option>
<option value="231">Tuvalu</option>
<option value="188">Uganda</option>
<option value="189">Ukraine</option>
<option value="190">United Arab Emirates</option>
<option value="191">United Kingdom</option>
<option value="1">United States</option>
<option value="192">Uruguay</option>
<option value="232">US Virgin Islands</option>
<option value="193">Uzbekistan</option>
<option value="233">Vanuatu</option>
<option value="194">Venezuela</option>
<option value="195">Vietnam</option>
<option value="197">Virgin Islands</option>
<option value="196">Virgin Islands (British)</option>
<option value="234">Wake Midway Island</option>
<option value="235">Wallis and Futuna</option>
<option value="198">Yemen</option>
<option value="199">Zambia</option>
<option value="236">Zimbabwe</option>